### ISSUE TITLE
spring boot 产生JAR无法加密，报错

### ISSUE THREAD

**Issue by lantianqiongfeng** [core-lib/xjar#12]
java.util.zip.ZipException: Unexpected record signature: 0X622F2123
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:260)
	at org.apache.commons.compress.archivers.jar.JarArchiveInputStream.getNextJarEntry(JarArchiveInputStream.java:56)
	at io.xjar.boot.XBootEncryptor.encrypt(XBootEncryptor.java:79)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:364)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:307)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:249)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:234)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:220)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:207)
	at com.ftvalue.XjarEncrypt.main(XjarEncrypt.java:17)

**Comment by lantianqiongfeng** [comment]
报错如下：
java.util.zip.ZipException: Unexpected record signature: 0X622F2123
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:260)
	at org.apache.commons.compress.archivers.jar.JarArchiveInputStream.getNextJarEntry(JarArchiveInputStream.java:56)
	at io.xjar.boot.XBootEncryptor.encrypt(XBootEncryptor.java:79)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:364)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:307)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:249)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:234)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:220)
	at io.xjar.boot.XBoot.encrypt(XBoot.java:207)
	at com.ftvalue.XjarEncrypt.main(XjarEncrypt.java:17)

**Comment by core-lib** [comment]
是不是这个问题
```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <!-- 需要将executable和embeddedLaunchScript参数删除，目前还不能支持对该模式Jar的加密！后面将会支持该方式的打包。 
    <configuration>
        <executable>true</executable>
        <embeddedLaunchScript>...</embeddedLaunchScript>
    </configuration>
    -->
</plugin>
```

**Comment by lantianqiongfeng** [comment]
我使用的是spring boot gradle来管理项目，不是用maven
能不能加QQ，帮忙看下

**Comment by core-lib** [comment]
可以啊  646742615

**Comment by lantianqiongfeng** [comment]
需要回答问题

**Comment by core-lib** [comment]
我加你吧

**Comment by lantianqiongfeng** [comment]
279583180
