### ISSUE TITLE
大神，您好， nohup 这种方式起不来呢, v2.0.6

### ISSUE THREAD

**Issue by sunyinhui** [core-lib/xjar#42]
[root@localhost project]# ll
-rw-r--r--.  1 root root         8 11月 20 13:57 a.key
-rw-------.  1 root root       598 11月 20 13:54 nohup.out
-rw-r--r--.  1 root root 214288661 11月 20 13:48 orange-encrypt.jar
[root@localhost project]# nohup java -jar ./orange-encrypt.jar --xjar.keyfile=./a.key | tailf -300 nohup.out
password:Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540)
	at io.xjar.XLauncher.<init>(XLauncher.java:143)
	at io.xjar.boot.XJarLauncher.<init>(XJarLauncher.java:18)
	at io.xjar.boot.XJarLauncher.main(XJarLauncher.java:22)
password:Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540)
nohup: 	at io.xjar.XLauncher.<init>(XLauncher.java:143)
	at io.xjar.boot.XJarLauncher.<init>(XJarLauncher.java:18)
	at io.xjar.boot.XJarLauncher.main(XJarLauncher.java:22)

**Comment by sunyinhui** [comment]
[root@localhost project]# java -jar ./orange-encrypt.jar --xjar.keyfile=./a.key
password:
这种其中也需要输入密码的，没有从文件中读取密码

**Comment by sunyinhui** [comment]
在大佬的指点下，是我没有写对密钥文件， 一开始我认为properties是写在spring里的，~^~
密钥文件
密钥文件采用properties的书写格式：

password: PASSWORD
algorithm: ALGORITHM
keysize: KEYSIZE
ivsize: IVSIZE
hold: HOLD
