### ISSUE TITLE
启动jar报java.lang.NoClassDefFoundError: sun/misc/URLClassPath

### ISSUE THREAD

**Issue by hoaven** [core-lib/xjar#49]
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/URLClassPath
        at io.xjar.boot.XBootClassLoader.<init>(XBootClassLoader.java:40)
        at io.xjar.boot.XJarLauncher.createClassLoader(XJarLauncher.java:31)
        at org.springframework.boot.loader.Launcher.createClassLoader(Launcher.java:64)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
        at io.xjar.boot.XJarLauncher.launch(XJarLauncher.java:26)
        at io.xjar.boot.XJarLauncher.main(XJarLauncher.java:22)
Caused by: java.lang.ClassNotFoundException: sun.misc.URLClassPath
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 6 more
难道是版本问题？

**Comment by core-lib** [comment]
你用什么版本

**Comment by 694551594** [comment]
我也是这个错。jdk11，jdk8没问题。

**Comment by jiangchengshi** [comment]
xjar版本：2.1.1
jdk版本：11
打包可以，运行报错：找不到类 sun.misc.URLClassPath。
