### ISSUE TITLE
某些第三依赖jar能不能不重新打包

### ISSUE THREAD

**Issue by ynp** [core-lib/xjar#52]
前端用户密码等敏感信息会进行RSA加密传输到后台处理。
后台解密会用到如bcprov-jdk15on包，但此包是带签名的，加密时，这类jar包能不能不重新打包，重新打包签名会失效报错。
直接替换掉加密后的bcprov-jdk15on包，启动会报错
`Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/bcprov-jdk15on-1.60.jar
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:108)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:69)
`
能不能给个提示如何处理？

**Comment by core-lib** [comment]
可以把 bcprov-jdk15on 这个包放在JDK或者其他地方去引用 目前还没解决这个问题

**Comment by wellRich** [comment]
可以使用exclude排除不加密的资源
