### ISSUE TITLE
打包没问题，运行报错："main" java.lang.NoClassDefFoundError: sun/misc/URLClassPath

### ISSUE THREAD

**Issue by hisan-web** [core-lib/xjar#54]
jdk 1.8
xjar 2.0.9

无法运行，提示：
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.xjar.boot.XBootClassLoader (file:/Users/jessica/Documents/Project%20Code/dwz/target/dwz-0.0.1-SNAPSHOT.xjar) to field java.net.URLClassLoader.ucp
WARNING: Please consider reporting this to the maintainers of io.xjar.boot.XBootClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/URLClassPath
	at io.xjar.boot.XBootClassLoader.<init>(XBootClassLoader.java:40)
	at io.xjar.boot.XJarLauncher.createClassLoader(XJarLauncher.java:31)
	at org.springframework.boot.loader.Launcher.createClassLoader(Launcher.java:65)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at io.xjar.boot.XJarLauncher.launch(XJarLauncher.java:26)
	at io.xjar.boot.XJarLauncher.main(XJarLauncher.java:22)
Caused by: java.lang.ClassNotFoundException: sun.misc.URLClassPath
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more`

**Comment by core-lib** [comment]
区分好你项目是 spring boot 启动方式 还是 普通的jar 
如果是spring boot 用 XBoot.encrypt 来加密
如果是普通的jar 用 XJar.encrypt 来加密
