### ISSUE TITLE
SpringBoot工程, 打包没问题，运行报错Exception in thread "main" java.lang.ClassNotFoundException: com.ccb.cloud.csrc.serverInfo.ServerInfoFetchApplication

### ISSUE THREAD

**Issue by come2099** [core-lib/xjar#62]
使用的版本如下：jdk 1.8  xjar 4.0.1
需要加密一个springBoot工程，加密没有问题，可以正常生成xjar.go和xjar.exe文件, 但是运行报错:
这个错误会偶尔出现，就是我同样的一个jar包，某次加密之后可能会正常运行； 重新加密之后（jar源文件无任何修改），可能会报错，大概成功率是10%左右：

C:\Users\Ferdinand\Desktop\key\decompile\encrypt2>xjar java -jar csc-server-info-fetch-dest.jar
Exception in thread "main" java.lang.ClassNotFoundException: com.ccb.cloud.csrc.serverInfo.ServerInfoFetchApplication
        at io.xjar.boot.XBootClassLoader.findClass(XBootClassLoader.java:89)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at io.xjar.boot.XJarLauncher.launch(XJarLauncher.java:26)
        at io.xjar.boot.XJarLauncher.main(XJarLauncher.java:22)
Caused by: java.io.IOException: javax.crypto.BadPaddingException: Given final block not properly padded
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:121)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:239)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:215)
        at io.xjar.XKit.transfer(XKit.java:124)
        at io.xjar.boot.XBootClassLoader.findClass(XBootClassLoader.java:81)
        ... 8 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:975)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:833)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at javax.crypto.Cipher.doFinal(Cipher.java:2048)
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:118)
        ... 12 more
panic: exit status 1

goroutine 1 [running]:
main.main()
        C:/Users/Ferdinand/Desktop/key/decompile/encrypt2/xjar.go:73 +0x482

![image](https://user-images.githubusercontent.com/48662292/88266468-db87e880-cd01-11ea-8fc4-acd2fe0733eb.png)
![image](https://user-images.githubusercontent.com/48662292/88266534-f0647c00-cd01-11ea-80dc-3334e7114dd7.png)

------------是不是XKit里面的加密算法有问题呢， Given final block not properly padded一般是加密算法有点问题啊------------

**Comment by come2099** [comment]
麻烦看看呢

**Comment by markchao** [comment]
我也有这个问题

**Comment by come2099** [comment]
> 我也有这个问题

目前我已经解决了
你的密码是不是包含中文？密码不要包含中文， 试一试呢

**Comment by come2099** [comment]
导致问题的原因是  我的密码包含中文, 去掉中文就好了  估计是中文支持不太好
