### ISSUE TITLE
为了保护核心代码，jar加密后用于IDEA开发，但IDEA启动springboot无法成功运行

### ISSUE THREAD

**Issue by qq499212485** [core-lib/xjar#68]
为了保护核心代码，我想将加密后的jar用在IDEA平时的开发上，让其他后端技术人员使用IDEA启动springboot可以正常使用，但是无法直接通过IDEA反编译看到核心代码。

目前已经成功加密了jar，但是使用IDEA运行的时候却无法运行，报错：
[19:47:31.387 ERROR] [org.springframework.boot.SpringApplication 837 reportFailure] - Application run failed org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/E:/cordova/dohuo_dev/src/main/resources/dohuo-lib-1.0.0-enc.jar!/com/adou/dohuo/modular/chat/mapper/AdChatMsgMapper.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: URL [jar:file:/E:/cordova/dohuo_dev/src/main/resources/dohuo-lib-1.0.0-enc.jar!/com/adou/dohuo/modular/chat/mapper/AdChatMsgMapper.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 26119

下面是我的操作过程：
1、使用XCryptos.encryption加密了jar部分代码

```
public static void encryption() throws Exception {
    XCryptos.encryption()
            .from("E:/src/main/resources/XXX-1.0.0.jar")
            .use("dohuo2020")
            .include("/com/adou/dohuo/modular/**/*ServiceImpl.class")
            .include("/com/adou/dohuo/modular/**/*Mapper.class")
            .include("/com/adou/dohuo/modular/**/*Mapper.xml")
            .to("E:/cordova/dohuo_new/src/main/resources/XXX-lib-1.0.0-enc.jar");
}
```

2、在另外一个项目中，创建了一个新的JarLauncher

```
public class DohuoJarLauncher implements XConstants {
    private final DohuoLauncher dohuoLauncher;

    public DohuoJarLauncher(String... args) throws Exception {
        this.dohuoLauncher = new DohuoLauncher(args);
    }

    public static void main(String... args) throws Exception {
        new DohuoJarLauncher(args).launch();
    }

    public void launch() throws Exception {
        XJarClassLoader xJarClassLoader;
        ClassLoader classLoader = this.getClass().getClassLoader();
        if (classLoader instanceof URLClassLoader) {
            URLClassLoader urlClassLoader = (URLClassLoader) classLoader;
            xJarClassLoader = new XJarClassLoader(urlClassLoader.getURLs(), classLoader.getParent(), dohuoLauncher.xDecryptor, dohuoLauncher.xEncryptor, dohuoLauncher.xKey);
        } else {
            ProtectionDomain domain = this.getClass().getProtectionDomain();
            CodeSource source = domain.getCodeSource();
            URI location = (source == null ? null : source.getLocation().toURI());
            String path = (location == null ? null : location.getSchemeSpecificPart());
            if (path == null) {
                throw new IllegalStateException("Unable to determine code source archive");
            }
            File jar = new File(path);
            URL url = jar.toURI().toURL();
            xJarClassLoader = new XJarClassLoader(new URL[]{url}, classLoader.getParent(), dohuoLauncher.xDecryptor, dohuoLauncher.xEncryptor, dohuoLauncher.xKey);
        }

        Thread.currentThread().setContextClassLoader(xJarClassLoader);
        Class<?> mainClass = xJarClassLoader.loadClass("com.adou.dohuo.DohuoApplication");
        Method mainMethod = mainClass.getMethod("main", String[].class);
        mainMethod.invoke((Object) null, (Object) this.dohuoLauncher.args);
    }
}
```

3、IDEA直接运行DohuoJarLauncher.main()，运行失败，报错：

```
[19:47:31.364 WARN ] [org.springframework.context.support.AbstractApplicationContext 559 refresh] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/E:/cordova/dohuo_dev/src/main/resources/dohuo-lib-1.0.0-enc.jar!/com/adou/dohuo/modular/chat/mapper/AdChatMsgMapper.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: URL [jar:file:/E:/cordova/dohuo_dev/src/main/resources/dohuo-lib-1.0.0-enc.jar!/com/adou/dohuo/modular/chat/mapper/AdChatMsgMapper.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 26119
[19:47:31.384 INFO ] [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener 136 logMessage] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[19:47:31.387 ERROR] [org.springframework.boot.SpringApplication 837 reportFailure] - Application run failed org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/E:/cordova/dohuo_dev/src/main/resources/dohuo-lib-1.0.0-enc.jar!/com/adou/dohuo/modular/chat/mapper/AdChatMsgMapper.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: URL [jar:file:/E:/cordova/dohuo_dev/src/main/resources/dohuo-lib-1.0.0-enc.jar!/com/adou/dohuo/modular/chat/mapper/AdChatMsgMapper.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 26119
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:452) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:315) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:276) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.mybatis.spring.mapper.ClassPathMapperScanner.doScan(ClassPathMapperScanner.java:181) ~[mybatis-spring-2.0.4.jar:2.0.4]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.scan(ClassPathBeanDefinitionScanner.java:254) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.mybatis.spring.mapper.MapperScannerConfigurer.postProcessBeanDefinitionRegistry(MapperScannerConfigurer.java:356) ~[mybatis-spring-2.0.4.jar:2.0.4]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:126) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at com.adou.dohuo.DohuoApplication.main(DohuoApplication.java:19) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at com.adou.dohuo.DohuoJarLauncher.launch(DohuoJarLauncher.java:54) [classes/:?]
	at com.adou.dohuo.DohuoJarLauncher.main(DohuoJarLauncher.java:23) [classes/:?]
Caused by: org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: URL [jar:file:/E:/cordova/dohuo_dev/src/main/resources/dohuo-lib-1.0.0-enc.jar!/com/adou/dohuo/modular/chat/mapper/AdChatMsgMapper.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 26119
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:60) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:429) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 23 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 26119
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:196) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:177) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:163) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:284) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:57) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:429) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 23 more
```

4、想问问如果想要达到在IDEA中运行需要如何进行修改？

5、该框架十分强力！感谢！

**Comment by dogourd** [comment]
请问是哪里的问题呢
