### ISSUE TITLE
加密后无法启动

### ISSUE THREAD

**Issue by idlesysman** [core-lib/xjar#73]
##### 1.版本
4.0.1
##### 2.加密代码:
```java
String password = "io.xjar";
XKey xKey = XKit.key(password);
XBoot.encrypt(
	"D:\\code\\othertarget\\infra.jar",
	"D:\\code\\othertarget\\infra.xjar",
	xKey);

```
##### 3.运行
```cmd
java -jar infra.xjar
```
##### 4.现象:
没有任何提示输入，但在等待用户输入,如果按多次回车，则报错
```
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at io.xjar.XLauncher.<init>(XLauncher.java:23)
        at io.xjar.boot.XExtLauncher.<init>(XExtLauncher.java:21)
        at io.xjar.boot.XExtLauncher.main(XExtLauncher.java:25)
```
##### 5.如果编译后运行
```
go build xjar.go
xjar java -jar infra.xjar
```
版本：go1.15.6
报错
```
Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 3867008848 in class file me/guijy/biz/infrastructure/BizInfraApplication
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at io.xjar.boot.XExtLauncher.launch(XExtLauncher.java:29)
        at io.xjar.boot.XExtLauncher.main(XExtLauncher.java:25)
panic: exit status 1

goroutine 1 [running]:
main.main()
        D:/code/other/Java/mis/biz-app/biz-infrastructure/target/xjar.go:73 +0x5ab
```

谢谢！

**Comment by doufum** [comment]
同样的问题，几个项目，其中一个就出现了这样的问题。
最近做了项目重构，本来这个项目一直使用了xjar进行加密，之前好好的。
重构之后，一部分代码拆分出去单独打包上传nexus，以依赖形式从nexus下载。
这样之后，打包出来的xjar执行就是报错
```
Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 1951653804 in class file
```

之前是v2.0.6，测试了后续的几个版本，都是报错。
直接使用java -jar 或 用go启动器来，也是同样的错误。

**Comment by jasonSunhu** [comment]
请问有解决这个问题吗

**Comment by sayago0002** [comment]
@ @

> 同样的问题，几个项目，其中一个就出现了这样的问题。 最近做了项目重构，本来这个项目一直使用了xjar进行加密，之前好好的。 重构之后，一部分代码拆分出去单独打包上传nexus，以依赖形式从nexus下载。 这样之后，打包出来的xjar执行就是报错
> 
> ```
> Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 1951653804 in class file
> ```
> 
> 之前是v2.0.6，测试了后续的几个版本，都是报错。 直接使用java -jar 或 用go启动器来，也是同样的错误。

老哥后来是放弃使用xjar了吗，我现在也遇到同样的问题了

**Comment by as7212325** [comment]
请问解决了吗 2023年问题依旧狗日的总监非得让用，什么垃圾加密方式

**Comment by sayago0002** [comment]
> 

没解决，已经放弃了

**Comment by iamxiaojianzheng** [comment]
> 同样的问题，几个项目，其中一个就出现了这样的问题。 最近做了项目重构，本来这个项目一直使用了xjar进行加密，之前好好的。 重构之后，一部分代码拆分出去单独打包上传nexus，以依赖形式从nexus下载。 这样之后，打包出来的xjar执行就是报错
> 
> ```
> Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 1951653804 in class file
> ```
> 
> 之前是v2.0.6，测试了后续的几个版本，都是报错。 直接使用java -jar 或 用go启动器来，也是同样的错误。

v2.0.7 尝试过吗？

**Comment by coderj09100724** [comment]
我也遇到同样问题，启动时报Incompatible magic value错误，寻找解决方式中

**Comment by sweet98912** [comment]
请问解决了吗？
