### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: Unexpected record signature: 0X622F2123

### ISSUE THREAD

**Issue by itlaodu** [core-lib/xjar#81]
XCryptos.encryption()的时候报错了，请教
Exception in thread "main" java.util.zip.ZipException: Unexpected record signature: 0X622F2123
	at org.apache.commons.compress.archivers.zip.ZipArchiveInputStream.getNextZipEntry(ZipArchiveInputStream.java:260)
	at org.apache.commons.compress.archivers.jar.JarArchiveInputStream.getNextJarEntry(JarArchiveInputStream.java:56)
	at io.xjar.boot.XBootEncryptor.encrypt(XBootEncryptor.java:84)
	at io.xjar.boot.XBootEncryptor.encrypt(XBootEncryptor.java:65)
	at io.xjar.XSmartEncryptor.encrypt(XSmartEncryptor.java:39)
	at io.xjar.XCryptos.encrypt(XCryptos.java:83)
	at io.xjar.XEncryption.to(XEncryption.java:160)
	at io.xjar.XEncryption.to(XEncryption.java:132)
	at com.test.jar.JarEncryption.main(JarEncryption.java:23)2123

**Comment by itlaodu** [comment]
这个问题解决了， 去掉了<executable>true</executable>，但启动的时候报错
D:\te>xjar java -javaagent:xjar-agent-hibernate-v1.0.0.jar -jar xxxxxxx.jar
panic: invalid jar with MD5

goroutine 1 [running]:
main.main()
        D:/te/xjar.go:47 +0x711

**Comment by shayne-chen** [comment]
> 这个问题解决了， 去掉了true，但启动的时候报错
> D:\te>xjar java -javaagent:xjar-agent-hibernate-v1.0.0.jar -jar xxxxxxx.jar
> panic: invalid jar with MD5
> 
> goroutine 1 [running]:
> main.main()
> D:/te/xjar.go:47 +0x711

I have the same problem

**Comment by limeiyang** [comment]
> > 这个问题解决了， 去掉了true，但启动的时候报错
> > D:\te>xjar java -javaagent:xjar-agent-hibernate-v1.0.0.jar -jar xxxxxxx.jar
> > panic: invalid jar with MD5
> > goroutine 1 [running]:
> > main.main()
> > D:/te/xjar.go:47 +0x711
> 
> I have the same problem

我也是这个问题...

**Comment by GitChenfan** [comment]
应该是没有重新build xjar.go导致的
